#!/usr/bin/env python3
"""Import recorded voice lines into the game.

Usage: python3 tools/voice/import.py <folder-or-zip> [...]
       python3 tools/voice/import.py --as <speaker> <folder-or-zip>

--as: the files came back numbered in the batch's order (audio_1.mp3, 002_audio_2.mp3 ...)
instead of by name; number N becomes that speaker's Nth line in script.csv.

Takes the mp3s named like the TTS batch files (erik_001.mp3, kearns_intercom_01.mp3 ...),
trims the silence off both ends, evens out the loudness, and writes them to
assets/voice/<speaker>/. Then rebuilds src/lore/voiceLines.js, which tells the game
which recording goes with which line and how long it is.

tools/voice/script.csv is the frozen list of lines (text, voice, filename) that was
sent out for recording, so file numbers never shift when the lore changes.
"""
import csv, json, os, subprocess, sys, tempfile, zipfile

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SCRIPT = os.path.join(ROOT, 'tools/voice/script.csv')
OUT = os.path.join(ROOT, 'assets/voice')
MANIFEST = os.path.join(ROOT, 'src/lore/voiceLines.js')

rows = {r['filename']: r for r in csv.DictReader(open(SCRIPT, encoding='utf-8'))}
speaker = lambda name: name.split('_')[0]

def clean(src, dst):
  # trim leading/trailing silence (keep a hair of air), normalise loudness, mono 24 kHz mp3
  trim = 'silenceremove=start_periods=1:start_threshold=-45dB:start_silence=0.04'
  af = f'{trim},areverse,{trim},areverse,loudnorm=I=-16:TP=-1.5:LRA=11'
  subprocess.run(['ffmpeg', '-v', 'error', '-y', '-i', src, '-af', af, '-ac', '1', '-ar', '24000',
                  '-c:a', 'libmp3lame', '-q:a', '4', dst], check=True)

def duration(p):
  r = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', p],
                     capture_output=True, text=True, check=True)
  return round(float(r.stdout.strip()), 2)

def sources(arg):
  if zipfile.is_zipfile(arg):
    tmp = tempfile.mkdtemp()
    zipfile.ZipFile(arg).extractall(tmp)
    arg = tmp
  for d, _, fs in os.walk(arg):
    for f in fs:
      if f.lower().endswith('.mp3') and not f.startswith('._'):
        yield os.path.join(d, f)

args = sys.argv[1:]
as_who = None
if args[:1] == ['--as']: as_who, args = args[1], args[2:]
order = [n for n in rows if speaker(n) == as_who] if as_who else []

def name_of(p):
  base = os.path.splitext(os.path.basename(p))[0]
  if not as_who: return base
  import re
  m = re.search(r'(\d+)$', base) or re.match(r'(\d+)', base)
  i = int(m.group(1)) if m else 0
  return order[i - 1] if 1 <= i <= len(order) else base

imported, unknown = 0, []
for arg in args:
  for p in sources(arg):
    if '__MACOSX' in p: continue
    name = name_of(p)
    if name not in rows: unknown.append(name); continue
    os.makedirs(os.path.join(OUT, speaker(name)), exist_ok=True)
    clean(p, os.path.join(OUT, speaker(name), name + '.mp3'))
    imported += 1

# rebuild the manifest from everything in assets/voice
lines = {}
for who in sorted(os.listdir(OUT)) if os.path.isdir(OUT) else []:
  for f in sorted(os.listdir(os.path.join(OUT, who))):
    name = f[:-4]
    if not f.endswith('.mp3') or name not in rows: continue
    lines.setdefault(who, {})[rows[name]['text']] = [name, duration(os.path.join(OUT, who, f))]

with open(MANIFEST, 'w', encoding='utf-8') as fh:
  fh.write('// =============================================================================\n')
  fh.write('// Recorded voice lines. GENERATED by tools/voice/import.py: don\'t edit by hand.\n')
  fh.write('// speaker -> line text -> [file in assets/voice/<speaker>/, seconds]\n')
  fh.write('// Lines without a recording keep the synthesized placeholder voice.\n')
  fh.write('// =============================================================================\n')
  fh.write('export const VOICE_LINES = {\n')
  for who, by in lines.items():
    fh.write(f'  {who}: {{\n')
    for text, v in by.items(): fh.write(f'    {json.dumps(text, ensure_ascii=False)}: {json.dumps(v)},\n')
    fh.write('  },\n')
  fh.write('};\n')

print(f'imported {imported} files; manifest has', {k: len(v) for k, v in lines.items()})
if unknown: print('not in the script (skipped):', unknown)
